In [1]:
import numpy as np

In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [7]:
skaler = np.array(90)

In [9]:
vektor = np.array([1,2,3,4,5,6])

In [11]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [17]:
print(skaler)

90


In [19]:
print(vektor)

[1 2 3 4 5 6]


In [21]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
