In [3]:
import numpy as np

In [5]:
vektor = np.array([0,2,4,5,6,7,8,15])

In [7]:
vektor[3]

5

In [9]:
vektor[0]

0

In [11]:
vektor[-1]

15

In [13]:
vektor[1:3]

array([2, 4])

In [15]:
vektor[:5]

array([0, 2, 4, 5, 6])

In [17]:
vektor[2:6:2]

array([4, 6])