In [3]:
import numpy as np

In [7]:
matris = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [9]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
matris[0]

array([1, 2, 3, 4])

In [13]:
matris[1]

array([5, 6, 7, 8])

In [15]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
matris[0,:]

array([1, 2, 3, 4])

In [21]:
matris[0,:2]

array([1, 2])

In [23]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [27]:
matris[0:4,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [29]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])