In [3]:
import numpy as np

In [5]:
liste = [1,2,3,4,5,6]

In [7]:
range(1_000_000)

range(0, 1000000)

In [11]:
milyon = np.arange(1_000_000)

In [13]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(5,10,2)

array([5, 7, 9])