In [1]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [24]:
np.linspace(0,20,10) # ( ilk , son , kac esit parcaya bolunecegi )

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [26]:
#ilk ve son eleman dahil oldugunu unutma

In [28]:
bol = np.linspace(5,25,15)

In [30]:
bol

array([ 5.        ,  6.42857143,  7.85714286,  9.28571429, 10.71428571,
       12.14285714, 13.57142857, 15.        , 16.42857143, 17.85714286,
       19.28571429, 20.71428571, 22.14285714, 23.57142857, 25.        ])