In [5]:
import numpy as np

In [7]:
matris = np.random.randint(0,10,(5,5))

In [9]:
matris

array([[2, 6, 7, 0, 1],
       [6, 6, 2, 8, 8],
       [3, 9, 5, 2, 0],
       [4, 2, 0, 5, 9],
       [9, 9, 0, 5, 8]])

In [11]:
matris > 5

array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [13]:
matris[matris>5]

array([6, 7, 6, 6, 8, 8, 9, 9, 9, 9, 8])

In [15]:
matris[matris<5]

array([2, 0, 1, 2, 3, 2, 0, 4, 2, 0, 0])

In [17]:
matris[matris==5]

array([5, 5, 5])

In [19]:
matris[matris==7].size

1

In [21]:
matris[matris!=7]

array([2, 6, 0, 1, 6, 6, 2, 8, 8, 3, 9, 5, 2, 0, 4, 2, 0, 5, 9, 9, 9, 0,
       5, 8])

In [23]:
matris

array([[2, 6, 7, 0, 1],
       [6, 6, 2, 8, 8],
       [3, 9, 5, 2, 0],
       [4, 2, 0, 5, 9],
       [9, 9, 0, 5, 8]])

In [25]:
matris%2==0

array([[ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True, False, False],
       [False, False,  True, False,  True]])

In [27]:
matris[matris%2==0]

array([2, 6, 0, 6, 6, 2, 8, 8, 2, 0, 4, 2, 0, 0, 8])

In [37]:
sifir = matris != 0

In [39]:
cift = matris % 2 == 0 

In [41]:
sifir , cift

(array([[ True,  True,  True, False,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [ True,  True, False,  True,  True],
        [ True,  True, False,  True,  True]]),
 array([[ True,  True, False,  True, False],
        [ True,  True,  True,  True,  True],
        [False, False, False,  True,  True],
        [ True,  True,  True, False, False],
        [False, False,  True, False,  True]]))

In [43]:
matris[sifir]

array([2, 6, 7, 1, 6, 6, 2, 8, 8, 3, 9, 5, 2, 4, 2, 5, 9, 9, 9, 5, 8])

In [45]:
matris[sifir & cift]

array([2, 6, 6, 6, 2, 8, 8, 2, 4, 2, 8])

In [47]:
bir = matris == 1

In [49]:
matris[cift | bir]

array([2, 6, 0, 1, 6, 6, 2, 8, 8, 2, 0, 4, 2, 0, 0, 8])

In [55]:
matris[(cift&sifir) |bir]

array([2, 6, 1, 6, 6, 2, 8, 8, 2, 4, 2, 8])